---

# Database settings.
db_user: "db_user"
db_name: "{{ application_name }}"
db_password: ee0Er8Hbg9


# Nginx settings.
nginx_server_name: localhost


# RabbitMQ settings.
rabbitmq_server_name: "{{ inventory_hostname }}"
rabbitmq_admin_user: admin
rabbitmq_admin_password: password
rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: password

# Celery settings.
celery_num_workers: 2
celery_application_settings_file: settings.local

# SMTP settings.
smtp_host: smtp.gmail.com
smtp_user: admin@example.com
smtp_password: mypassword

# Application settings.
django_settings_file: settings.local
django_secret_key: xxx

#run_django_syncdb: yes
#run_django_south_migration: yes
#run_django_collectstatic: yes